-- Moodon 테이블의 RLS 비활성화
ALTER TABLE mo_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE mo_product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE mo_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE mo_send_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE mo_send_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE mo_tracking_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE mo_compose_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE mo_settings DISABLE ROW LEVEL SECURITY;
